<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [8]:
def InputMatrix(name):
    X = []
    i = 0
    print("\nUse coma to seperate values and press S to exit")
    while True:
        i += 1
        row = input('\n please enter values of row %s of Matrix %s : ' %(i, name))
        if row == 'S':
            break
        else:
            strList = row.split(',')
            X.append(list(map(int, strList)))
    return X
Result=[]

A = InputMatrix('X')
B = InputMatrix('Y')

for m in range(len(A)):
    l=[]
    for n in range(len(B[0])):
        l.append(0)
    Result.append(l)
try:
    if(len(A)!=len(B[0])):
        raise ValueError("Exception")
    for i in range(len(A)):
   # iterate through columns of Y
        for j in range(len(B[0])):
       # iterate through rows of Y
            for k in range(len(B)):
                Result[i][j] += A[i][k] * B[k][j]
except ValueError:
    print("\nMatrix multiplication is not possible")
                
if(len(A) == len(B[0])):
    print("\noutput of the matrix is")
    print("***********************")
    for r in Result:
        print(r)


Use coma to seperate values and press S to exit

 please enter values of row 1 of Matrix X : 1,1

 please enter values of row 2 of Matrix X : 2,2

 please enter values of row 3 of Matrix X : S

Use coma to seperate values and press S to exit

 please enter values of row 1 of Matrix Y : 1,1

 please enter values of row 2 of Matrix Y : 2,2

 please enter values of row 3 of Matrix Y : S

output of the matrix is
***********************
[3, 3]
[6, 6]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [1]:
from random import uniform
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
#Reference: https://stackoverflow.com/questions/57892112/select-a-number-randomly-with-probability-proportional-to-its-magnitude-from-the


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    sum=0
    total_sum=[]
    for i in range(len(A)):
        sum = sum + A[i]
        total_sum.append(sum)
    list1=[]
    
    r = int(random.uniform(0,sum))
    number=0
    for index in range(len(total_sum)):
        if(r>=total_sum[index] and r<total_sum[index+1]):
            print(A[index+1])
            return A[index+1]

def sampling_based_on_magnitued():
    A = [0,5,27,6,13,28,100,45,10,79]
    v = dict()
    print(A,sum(A))
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        #print(number)
        if number in v:
            v[number] += 1
        else:
            v[number] = 1
    print(v)
    
sampling_based_on_magnitued()

[0, 5, 27, 6, 13, 28, 100, 45, 10, 79] 313
100
79
100
100
45
79
100
100
45
10
100
28
27
28
100
100
13
79
79
45
100
100
100
79
100
45
28
79
79
10
79
79
10
100
6
27
10
100
28
45
27
79
27
79
28
10
100
45
13
100
28
27
45
28
79
45
79
27
28
45
100
45
79
79
100
79
28
100
100
100
28
45
28
45
79
27
100
79
79
79
79
79
79
28
45
28
79
79
45
79
79
79
79
45
79
79
79
45
27
{100: 22, 79: 32, 45: 16, 10: 5, 28: 13, 27: 8, 13: 2, 6: 1}


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [4]:
import re
def replace_digits(input_string): 
    input_string = re.sub("[^A-Za-z0-9]","",input_string)
    for ele in input_string: 
        if ele.isdigit(): 
            input_string = input_string.replace(ele, "#")
        else:
            input_string = input_string.replace(ele,"") 
    return(input_string) 

input_string = input('\n please enter the string')
print("Input you entered : " + str(input_string))  
output = replace_digits(input_string)
print("Output String : " + str(output))


 please enter the stringa2b3c4
Input you entered : a2b3c4
Output String : ###


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [1]:
S=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
max5=[]
min5=[]
m1=max(marks)
m2=min(marks)
d=m1-m2
def find_max(marks):
    print("Students with top five ranks are as follows")
    while len(max5) <= 4:
        max5.append(max(marks))
        print(S[marks.index(max(marks))], ':', max(marks))
        marks=[i for i in marks if i not in max5]
    

def find_min(marks):
    print("Students with least five ranks are as follows")
    while len(min5) <= 4:
        min5.append(min(marks))
        print(S[marks.index(min(marks))], ':', min(marks))
        marks=[i for i in marks if i not in min5]
        
def find_percentile(marks,d):
    print("Students between 25th and 75th percentile are as follows")
    pre_25 = d*0.25
    pre_75 = d*0.75
    for i in sorted(marks):
        if pre_25 < i < pre_75 :
                print(S[marks.index(i)], ':', i)

find_max(marks)
find_min(marks)
find_percentile(marks,d)


Students with top five ranks are as follows
student8 : 98
student9 : 80
student2 : 78
student4 : 48
student5 : 47
Students with least five ranks are as follows
student3 : 12
student3 : 14
student7 : 35
student4 : 43
student1 : 45
Students between 25th and 75th percentile are as follows
student9 : 35
student6 : 43
student1 : 45
student7 : 47
student5 : 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [2]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    cosine_dist = []
    for a, b in S:
        num = a * P[0] + b * P[1]
        den = math.sqrt(a ** 2 + b ** 2) * math.sqrt(P[0] ** 2 + P[1] ** 2)
        cosine_dist.append(math.acos(num/den))
    X = cosine_dist
    Y = [S for S in sorted(zip(S,X), key=lambda i:i[1])]
    k = Y[:5] 
    for i, j in k:
        print(i)
    #return closest_points_to_p  # its list of tuples

S = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
P= (3,-4)
points = closest_points_to_p(S, P)
#print() #print the returned values

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [3]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(Red,Blue,Lines):
    equation1 = []
    equation2 = []
    for k in Lines:
        a=k[0];b=k[2]+k[3];c=k[5]+k[6]
        n = [];m=[]
        for i in Red:
            x1=i[0];y1=i[1]
            eq1 = int(a) * int(x1) + int(b) * int(y1)-int(c)
            n.append(eq1)
        equation1.append(n)
        for j in Blue:
            x2=j[0];y2=j[1]
            eq2 = int(a) * int(x2) + int(b) * int(y2)-int(c)
            m.append(eq2)
        equation2.append(m)
    print(equation1)
    print('----------------------------------------------------------------------')
    print(equation2)
    print('----------------------------------------------------------------------')
    p=[]
    for i,j in zip(equation1,equation2):
        q = []
        for k,l in zip(i,j):
            x=k*l
            if x<0:
                q.append(x)
        p.append(q)
    print(p)
    for i in p:
        if len(i)==5:
            print('YES')
        else:
            print('NO')


Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

i_am_the_one(Red, Blue,Lines)


[[2, 3, 6, 6, 3], [0, 1, 2, -2, -5], [4, 5, 7, 5, 2], [1, 1, 2, 4, 4]]
----------------------------------------------------------------------
[[-3, -3, -5, -4, -2], [-1, 1, -1, -2, 4], [1, 2, 0, 0, 4], [-1, -2, -2, -1, -3]]
----------------------------------------------------------------------
[[-6, -9, -30, -24, -6], [-2, -20], [], [-1, -2, -4, -4, -12]]
YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [4]:
def curve_smoothing(x, a, b):
    if a == -1:
        v = float(x[b])/(b+1)
        for i in range(a+1,b+1):
            x[i] = v
    elif b == -1:
        v = float(x[a])/(len(x)-a)
        for i in range(a, len(x)):
            x[i] = v
    else:
        v = (float(x[a])+float(x[b]))/(b-a+1)
        for i in range(a,b+1):
            x[i] = v
    return x

def compute_dashes(text):
    x = text.replace(" ","").split(",")
    m = [i for i, v in enumerate(x) if v != '_']
    # Starting with _ ?
    if m[0] != 0:
        m = [-1] + m
    # Ending with _ ?
    if m[-1] != len(x)-1:
        m = m + [-1]
    # run over all the pairs
    for (a, b) in zip(m[:-1], m[1:]): 
        curve_smoothing(x,a,b)          
    return x

# Test cases
S = ["_,_,_,24",
         "40,_,_,_,60",
     "_,_,30,_,_,_,50,_,_"]

for i in S:
    print (compute_dashes(i))


[6.0, 6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0, 20.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [5]:
def compute_conditional_probabilites(F,S):
    numerator,denominator,prob=0,0,0
    for i in range(len(A)):
        if(A[i][1]==S):
            denominator=denominator+1
            if(A[i][0]==F):
                numerator=numerator+1
    prob=numerator/denominator
    print('P(F={}|S=={})={}/{}({})'.format(F, S, numerator, denominator ,prob))

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
for f in ['F1', 'F2', 'F3', 'F4', 'F5']:
    for s in ['S1', 'S2', 'S3']:
        compute_conditional_probabilites(f,s)


P(F=F1|S==S1)=1/4(0.25)
P(F=F1|S==S2)=1/3(0.3333333333333333)
P(F=F1|S==S3)=0/3(0.0)
P(F=F2|S==S1)=1/4(0.25)
P(F=F2|S==S2)=1/3(0.3333333333333333)
P(F=F2|S==S3)=1/3(0.3333333333333333)
P(F=F3|S==S1)=0/4(0.0)
P(F=F3|S==S2)=1/3(0.3333333333333333)
P(F=F3|S==S3)=1/3(0.3333333333333333)
P(F=F4|S==S1)=1/4(0.25)
P(F=F4|S==S2)=0/3(0.0)
P(F=F4|S==S3)=1/3(0.3333333333333333)
P(F=F5|S==S1)=1/4(0.25)
P(F=F5|S==S2)=0/3(0.0)
P(F=F5|S==S3)=0/3(0.0)


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [6]:
def string_features(s0, s1):
    word2=[]
    word1=[]
    s0 = s0.split(" ")
    s1 = s1.split(" ")
    if(len(s0)==len(s1)):
        for letter in s0:
            if letter not in s1:
                word2.append(letter)
        print(word2)
    if(len(s0)==len(s1)):
        for letter in s1:
            if letter not in s0:
                word1.append(letter)
        print(word1)
    return len(list(set(s0)&set(s1)))
S = "the first column F will contain only 5 uniques values"
T = "the second column S will contain only 3 uniques values"
result = string_features(S,T)
print(result)


['first', 'F', '5']
['second', 'S', '3']
7


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [7]:
import math
def compute_log_loss(A):
    m={}
    x=[]
    for i in range(len(A)):
        m[i] = (A[i][0])*math.log10(A[i][1])+(1-A[i][0])*math.log10(1-A[i][1])
    x=sum(m.values())
    x=x*(-1/len(A))
    return x

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print('Log loss:{}' .format(loss))

Log loss:0.42430993457031635
